### ISSUE TITLE
[project-2a] Character Creator / rpg-me promotional tool

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1414]
**PROJECT MUST BE COMPLETED USING THE HAX TOOLING TO ENSURE WE ARE WRITING CODE USING PLATFORM LEVEL WEB COMPONENTS. SUBMISSIONS DONE IN TOOLING AND TECHNOLOGY NOT LIT.DEV BASED WILL NOT BE EVALUATED.**

# HAX start
```bash
npm install --global @haxtheweb/create
hax start
```

The scope of this project is to create a stand alone app called `rpg-me` which the best solution will be hooked up to rpg-me.hax.cloud and linked to as part of our community / engagement sections of the haxtheweb.org documentation site.

# rpg-me

# High level requirements
- Character builder / attribute select screen from a video game
- rpg-character must be used
- wiredjs elements must be used
- Need to be able to use form inputs to remix and see the character update
- Need to be able to share this via a URL which pre-populates the settings

## rpg-character
- we've seen him before, but it's an actual tag. @haxtheweb/rpg-character
- This character comes with three ways it can be used. A `seed` property which randomly generates the items. For example, writing `<rpg-character seed="cool name"></rpg-character>` will produce the same thing every time as far as character it picks
- The additional way is to be able to define things like `<rpg-character accessories="3" hatcolor="5"></rpg-character>`
- A last way allows for setting all of the values as a literal seed value used to render the dude. `<rpg-character literalseed seed="1234567899"></rpg-character>`. This is read as `accessories="1"` (the 1st value) and `hatcolor="9"` (the last value)
- https://cdn.hax.cloud/storybook/?path=/story/system-rpg-character--rpg-character-story shows how some of these values can be leveraged to generate HTML
- Code for the element: https://github.com/haxtheweb/webcomponents/blob/master/elements/rpg-character/src/rpg-character.js
- `height` and `width` can be set to numerical values in order to make it larger or smaller (useful for responding to the size of the screen)

## wiredjs
WiredJS allows you to create rough UIs that are randomly generated in sketch lines. This creates an intentionally rough / undesigned feel which is great for prototyping discussions. It also matches some of the HAX aesthetic and is a good example of needing to account for existing component libraries when we go to build something.
- It provides, buttons, cards, and most importantly **designed inputs** which 
- How to install / usage example https://github.com/rough-stuff/wired-elements/?tab=readme-ov-file#install
- Docs for the elements in question https://github.com/rough-stuff/wired-elements/tree/master/docs (for docs of each)

## requirements
**PROJECT MUST BE COMPLETED USING THE HAX TOOLING TO ENSURE WE ARE WRITING CODE USING PLATFORM LEVEL WEB COMPONENTS. SUBMISSIONS DONE IN TOOLING AND TECHNOLOGY NOT LIT.DEV BASED WILL NOT BE EVALUATED.**
We need to create a remixable character selection screen that allows for the sharing of the character on social sites. This can easily be screenshoted for use on social media and also can help raise awareness of the project.

### The specific techniques of web development you will be demonstrating through this project:
- Using existing work
- Responding to events from input fields; reacting by updating the rpg-character
- Ability to integrate with the URL bar parameters so that 'share' links can be generated which prepopulate the settings
- State management via the URL change but also updating so users see their changes instantly
- Design work to support mobile and desktop layouts

### Visual requirements
- It needs to use wiredJS elements in order to visually look like a prototyping system
- All inputs should be using WiredJS
- DDD should be used for spacing / color usage (WiredJS does not define these)
- Two column on desktop. Character (very large) on left, Inputs in a big table on the right. Tweak the inputs in the table, see the changes to the character happen live
- The seed being generated should be written below the character so people know how it was generated
- Color usage should help imply that this is visually different (panel 1 vs panel 2) and be visually appealing
- Link provided to this issue

### Input requirements
- All `aspects of the character` need to be modifiable via inputs:
  - accessories: 0 - 9
  - base: 1 or 5 (Male 0-4, Female 5-9)
  - leg (ignored, set to 0 and disable / hide input)
  - face: 0 -5
  - faceitem: 0 - 9
  - hair: 0 - 9
  - pants: 0 - 9
  - shirt: 0 -9
  - skin: 0-9
  - hatcolor: 0-9
- hat can be one of the following:
  "none" (this defaults to my hat)   
  "bunny",
  "coffee",
  "construction",
  "cowboy",
  "education",
  "knight",
  "ninja",
  "party",
  "pirate",
  "watermelon"
- fire (checkbox) for if the character is on fire
- walking for if the character moves
- circle for if the character has a circle around it
- When an input changes, it needs to update the associated property of the character

### Share requirements
- We need to be able to click "share" which will copy a link to the user's clipboard / show them the link to copy
- this link will need to be something like `{locationofapp}/?seed=1501111111&hat=random&fire=true`
- `seed` will need read in when the program starts to check if it is set. If it is set it needs to set `<rpg-character initialseed seed="${value}"></rpg-character>`
- When changing the inputs to modify the character, this seed value needs updated so that we can share exactly what we are seeing.
- This value is 10 digits in length and corresponds with the keys for settings on the character in the order listed previously for `aspects of the character`

## Comps / Inspiration
![image](https://github.com/user-attachments/assets/f149e773-0f36-40ff-989b-ee6926b0d10d)
![image](https://github.com/user-attachments/assets/98a88830-053f-4be4-88f9-0c6e06463be9)
![image](https://github.com/user-attachments/assets/73289543-72fb-4089-a9b2-9b81ca7dcec8)
![image](https://github.com/user-attachments/assets/8a24318e-68af-49a0-b094-afb2c074fc78)
![image](https://github.com/user-attachments/assets/24b9b2d9-4fb4-4285-8793-cd0eabb15aab)

# Rubric
This is worth **20% of your overall grade**
- Check in 1 is worth 2%
- Check in 2 is worth 3%
- The final project turned in is worth 15%

## Baseline assumption to any submission to receive attention (0%)
- Is it using wiredJS / rpg-character correctly?
- Is it published to vercel and the source is publicly available?
- Is the repo set up correctly using the conventions we've used all semester?

## Design (5%)
- Are inputs used in an accessible manner?
- Is it using appropriate wiredJS elements? Do they work together appropriately for the form with the correct data inputs?
- On mobile do we size appropriately?
- Does it look good on a desktop with the character sized such that it is visible?

## State Management (10%)
- Are appropriate inputs selected and data types matching what is expected based on select vs bool?
- When inputs are changed, does the character update instantly to reflect this?
- When inputs are changed, does the share link change?
- When defaults are loaded from the URL, does the character AND inputs change to reflect this?
- Can you share to different platform with it populating the URL to pass to those platforms? Does this work on 3 different platforms (Insta, X, LinkedIn, don't care, pick 3 services)

**Comment by Vmagz807** [comment]
I'll be doing this issue
https://github.com/Vmagz807/Project-2-RPG

**Comment by nrousseau4** [comment]
I'll be doing this issue
https://github.com/nrousseau4/rpg-me

**Comment by spfrha** [comment]
I'll be doing this issue
https://github.com/spfrha/rpg-me

**Comment by Pbauer34** [comment]
I will be doing this issue
https://github.com/Pbauer34/project2a-rpg

**Comment by ShyGuy2712** [comment]
I'm doing this issue
[https://github.com/ShyGuy2712/rpg-me](url)

**Comment by Eglicky** [comment]
https://github.com/Eglicky/rpg-new

**Comment by scottdgarciajr** [comment]
I'll be doing this issue https://github.com/scottdgarciajr/rpg-me

**Comment by Marcus-44** [comment]
https://github.com/Marcus-44/rpg-project1

**Comment by Cory-Z** [comment]
https://github.com/Cory-Z/Project-2.git

**Comment by Lil-02** [comment]
https://github.com/Lil-02/project-2a.git

**Comment by IanDob26** [comment]
I'm doing this issue 
https://github.com/IanDob26/project-2

**Comment by kkeksbtw** [comment]
I'll be doing this issue 
https://github.com/kkeksbtw/c-creator

**Comment by laiya-m** [comment]
https://github.com/laiya-m/rpg-me.git

**Comment by PSUEberly** [comment]
I'm doing this one
https://github.com/PSUEberly/project-two

**Comment by eb0t18** [comment]
https://github.com/eb0t18/rpg-me)

**Comment by chirasvigowda** [comment]
https://github.com/chirasvigowda/rpg-me.git

**Comment by dashawnpaige27** [comment]
I'm doing this issue:

[](https://github.com/dashawnpaige27/c-creator)

**Comment by ade5239** [comment]
I'll do this issue 
https://github.com/ade5239/rpg-me

**Comment by dashawnpaige27** [comment]
I'm doing this issue: 

https://github.com/dashawnpaige27/c-creator

**Comment by Ilikefish01** [comment]
I'm doing this:

https://github.com/Ilikefish01/rpg-me

**Comment by Sultanov134** [comment]
I will do rpg-me
https://github.com/Sultanov134/hax-rpg

**Comment by jno-de** [comment]
https://github.com/jno-de/rpg-me

**Comment by mja6635** [comment]
https://github.com/mja6635/project-2-156

**Comment by tay3434** [comment]
https://github.com/tay3434/rpg-character/commit/668284754df5d6a06b8726ea66681a6aabdb99f3

**Comment by cjfontaine27** [comment]
I'll be doing this issue: https://github.com/cjfontaine27/project-2a

**Comment by DylanConnor28** [comment]
https://github.com/DylanConnor28/project-2.git

**Comment by Gerritbandison** [comment]
I will be doing this issue

**Comment by tas6466** [comment]
https://github.com/tas6466/rpg-me

**Comment by syd18b** [comment]
https://github.com/syd18b/rpg-me

**Comment by xTyten** [comment]
https://github.com/[xTyten/ist-256-project-2](https://github.com/xTyten/ist-256-project-2)

**Comment by Lil-02** [comment]
https://github.com/Lil-02/rpg-me.git

reposting casue i remade my repo

**Comment by btopro** [comment]
https://rpg-me.hax.cloud/ congrats. This has already been roped into our network of projects based on work found here.
