### ISSUE TITLE
Memory Use Cases

### ISSUE THREAD

**Issue by WilliamMRose** [haxtheweb/issues#1794]
From this morning's riff with Bryan:

**Short-Term**
- New user (first time on system)
- Inactive user after X seconds
- Prompt to save page after X amount of work

**Long Term**
- User history shows frequent saving; don't prompt
- Track user skill growth (scale of 1-10); prompting fades accordingly
- Monitor authoring patterns, suggest media-specific phased activity for greater efficiency..."Your working style/efficiency shows..."

**Combined Use**
- Short Term: User just invoked X object
- Long Term: User has never used object before
- Action proactively fires quick tutorial link

**Odds and ends**
- Consider a "dismiss option" for user opting out of prompting (thanks/no thanks)
- Student use of Merlin! Much to think about. Scaffolding can be applied to a host of situations in which student behavior can be interpreted.

**Comment by btopro** [comment]
this was used to break out into other issues and discussions all under User Scaffolding
