### ISSUE TITLE
[bug] Background colors do not apply to blockquote

### ISSUE THREAD

**Issue by WilliamMRose** [haxtheweb/issues#1834]
Location: https://iam.hax.psu.edu/bmr1/sites/haxcellence/page-2/research-evidence-base
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1358x893
Battery: 100%
Connection: 4g
Bug you experienced: Confirmed this with Peter. Create a blockquote and choose any background color from the menu, the background will not change color.

**Comment by btopro** [comment]
fixed
