### ISSUE TITLE
block-quote / team-member style that supports an image

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#1915]
![image](https://github.com/elmsln/issues/assets/329735/451eae48-0a33-4ec8-af9e-3debd4fdd357)

**Comment by btopro** [comment]
filter + color + quote + image

**Comment by btopro** [comment]
@zdodson21 make sure to wire this up to HAX via haxProperties. json file under `/lib/`

Shouldn't be terribly difficult given how this works. Could be entirely property driven. You can also use `>` developer commands to forcibly load a schema definition so that you can play with it under `yarn run hax` place it on the page and modify the form

**Comment by zdodson21** [comment]
![image](https://github.com/user-attachments/assets/6a39cdf6-3122-46a7-ad31-259cc17454df)

Somewhat working currently, some issues with spacing in text for some reason but it's at least there.

**Comment by btopro** [comment]
Text-align needs a default or it inherits justified

**Comment by btopro** [comment]
DDD sets this by default so if you don't set it that's what you get

**Comment by zdodson21** [comment]
Much better

![image](https://github.com/user-attachments/assets/471415e4-143d-4369-8307-3fe6fbbe757e)
![image](https://github.com/user-attachments/assets/7dc22537-8946-4d96-9444-bd4dc99c4ae2)

**Comment by btopro** [comment]
Agreed. Make sure it supports font and color in DDD search for "designSystem": parameter to find an example implementing it. Should be something like

{ primary: true, font: true }

**Comment by btopro** [comment]
added directly into the invent theme
