### ISSUE TITLE
deploy and run HAXCMS [bug] User report from HAX daemon

### ISSUE THREAD

**Issue by andyux01** [haxtheweb/issues#2011]
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.https://tik2.pesanweb.id/build/es6/node_modules/@lrnwebcomponents/dynamic-import-registry/dynamic-import-registry.js
![hax hosting](https://github.com/haxtheweb/issues/assets/165729854/67c49aed-95b2-426a-8f27-6d4a24ac75de)

Location: https://tik2.pesanweb.id/build/es6/node_modules/@lrnwebcomponents/wc-autoload/wc-autoload.js
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
OS: Windows - 8GB RAM - 4 cores
Screen: 1920x1080
Window size: 1700x991
Battery: 100%
Connection: 4g
Bug you experienced:
I install from hosting with drag drop hax v. 8 release

**Comment by btopro** [comment]
it appears the build directory is not installed or else it would find those files. What hosting provider is this with and can you verify that all files have been pushed up to the server?

**Comment by andyux01** [comment]
ok, right build folder 

how about this

![image](https://github.com/haxtheweb/issues/assets/165729854/c87f6773-45df-4250-9bf9-b7616a3fcf51)

**Comment by btopro** [comment]
403 on a json file. Verify that file is there and then that there's nothing preventing the directory from being read. Possible need to chmod the files in question to access. Did it make the site if you refresh the dashboard?

**Comment by andyux01** [comment]
after make site/course

![image](https://github.com/haxtheweb/issues/assets/165729854/48eeb8c4-a828-43b0-9cff-495ae68c4ee2)

**Comment by andyux01** [comment]
what different ddev and from copas haxcmsmaster.zip to hosting? in gitpod can run.

![image](https://github.com/haxtheweb/issues/assets/165729854/d1e92177-d76d-4f1d-a84f-c5ad09dfbeb3)
