### ISSUE TITLE
how to deploy with 11ty

### ISSUE THREAD

**Issue by abiumi1** [haxtheweb/issues#2012]
can not start and build

![image](https://github.com/haxtheweb/issues/assets/153793202/ce04d0b8-d26d-4cfb-93d6-912644e74c66)

![image](https://github.com/haxtheweb/issues/assets/153793202/d32b5934-5d39-44ec-8336-4b2bfd53f855)

**Comment by btopro** [comment]
What os?

**Comment by btopro** [comment]
updated to use modern assets and build routines. Just tested it and it's now working to deliver the hax11ty doc site itself
- https://github.com/haxtheweb/hax11ty - README updated for how to use
- https://oer.hax.psu.edu/bto108/sites/haxcellence/documentation/hax11ty  details in our docs on what this is
- https://haxtheweb.github.io/hax11ty/  --  site built using the tooling itself
