### ISSUE TITLE
Need some data policy widget as part of the AI agent. 

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#2038]
In discussion with @djfusco and @cgldevel the idea of data retention came up, specifically that an advantage to our approach is students NOT giving data over to feed the AI overlords. This made me think that we probably should have something visually added to the UI about whether or not the conversation is being recorded, possibly even a setting for NOT recording. This would require a UI tweak accounting for on @zdodson21 part but also an API accounting for on @djfusco part.

- requests need the ability to be 'off the record'
- visual indicator implying that the conversation is 'on the record' for the user's benefit only and that data is not shared with other users / agents

This is just to start this conversation since there's probably more to it but wanted to make sure it was captured from yesterday

**Comment by zdodson21** [comment]
![image](https://github.com/haxtheweb/issues/assets/91283128/0099eee9-2076-4616-b731-689818b9eb01)

![image](https://github.com/haxtheweb/issues/assets/91283128/a804f160-2387-4065-943d-7280b36a0ad3)

Here's some rough screenshots. Added a `dataCollectionEnabled` variable which by default is set to true, and can be switched to `false` by pressing the "Data Collection" button. Will modify the AI request code when possible :D
