### ISSUE TITLE
[hax editor] Outline designer accessibility - white text on white background

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2066]
I noticed a few instances of white/bright text on a white background when navigating the outline designer.  Pictured are the three/four buttons at the top which are unreadable and I don't see any tooltip text when hovering over them so not sure what they say.  Not pictured is when I hover over the list items, the white page name text remains white and becomes a bit unreadable as well as the background fades into white.

![Screenshot 2024-07-20 122949](https://github.com/user-attachments/assets/8a76cde4-e860-437b-aabf-2ca3c9bf2ad4)

**Comment by btopro** [comment]
What browser as it appears you have activated dark mode in that dialog but not in the system itself

**Comment by zdodson21** [comment]
Can confirm that this issue occurs at least in FireFox. In the light mode screenshot, the username in the upper right-hand corner also does not appear to be the correct color to contrast light mode.

![Screenshot 2024-07-22 at 08-57-04 Article 1](https://github.com/user-attachments/assets/7530fdf5-4610-4d01-9a3f-c296a41cc722)
![Screenshot 2024-07-22 at 08-57-24 Article 1](https://github.com/user-attachments/assets/725e97d4-4a93-4de0-b990-ca48563d3963)

**Comment by btopro** [comment]
yeah I'll assume it's a `light-dark` issue like was run into previously

**Comment by zdodson21** [comment]
I just took care of the issue with the username appearing incorrectly on the right side of the editor ui. That will be part of my pull request later today. I did not look into the original contrast issue this issue was made for yet however.

**Comment by whatsacomputertho** [comment]
Yeah can confirm I was using Firefox.  Lmk if more info needed and I can dig into that as well

**Comment by whatsacomputertho** [comment]
Thanks all for the quick response 👏🏻🎉

**Comment by btopro** [comment]
9.0.2 Is out and doesn't include this fix but next bump will. Npx or init again to work on your site and it should ask you to get the latest which fixes all of the node publishing based issues. Thank you for the feedback

**Comment by btopro** [comment]
@zdodson21 want to take a stab at the text contrast issue today? Most likely it's related to light dark not being as widely supported as I had hoped and we just need a better default / fallback

**Comment by zdodson21** [comment]
Yeah I can take a look at it. Can handle that after implementing dark mode into `chat-agent`.
