### ISSUE TITLE
[hax editor] Exception while loading insights dashboard

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2067]
I see the following console errors when attempting to load the insights dashboard via my local editor.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://haxapi.vercel.app/api/apps/haxcms/insights. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.

Request failed TypeError: NetworkError when attempting to fetch resource.

Uncaught (in promise) TypeError: e is null
```

Drilling down, `e` seems to refer (possibly?) to [this line in `haxcms-site-insights.js`](https://github.com/haxtheweb/webcomponents/blob/15f11199b1dfb605277b913a93a6ec10e0051cee/elements/haxcms-elements/lib/core/haxcms-site-insights.js#L612).
```
            <lesson-highlight icon="editor:insert-drive-file">
              <p slot="title">${e.pages?e.pages:s`0`} ${this.t.pages}</p>
              <p>${e.objectives} ${this.t.learningObjectives},
              ${e.authorNotes} ${this.t.authorNotes},
              ${e.specialTags} ${this.t.specialElements},
              ${e.dataTables} ${this.t.dataTables},
              ${e.headings} ${this.t.headings}</p>
            </lesson-highlight>
```

**Comment by btopro** [comment]
support for local dev path (via node) which is not in need of rewriting our environment to point to local version. This is a dividing line as to why we should maintain some kind of forced 'demo' space for local testing but at least now MFR is able to detect nodejs and keep w/ the open-apis instead of assuming local
