### ISSUE TITLE
[bug] Bulleted lists do not save when placed within a column

### ISSUE THREAD

**Issue by WilliamMRose** [haxtheweb/issues#2073]
Location: https://iam.hax.psu.edu/bmr1/sites/haxcellence/foster-student-engagement
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1920x1080
Window size: 1564x932
Battery: 100%
Connection: 4g
Bug you experienced: Have repeatedly experienced this. I can create a list within a column, but the change will not save...just disappears. https://iam.hax.psu.edu/bmr1/sites/haxcellence/foster-student-engagement

**Comment by btopro** [comment]
https://oer.hax.psu.edu/bto108/sites/leanstartup/new-item/now-you-try

**Comment by btopro** [comment]
dup of #982
