### ISSUE TITLE
[bug] Color contrast not working for some text elements

### ISSUE THREAD

**Issue by zdodson21** [haxtheweb/issues#2076]
Text in a new site (while in editor) does not contrast with its background when browser (tested both FireFox and Chrome) are in dark mode (and also in light mode for Chrome). Here is a table to show what does have good contrast and what does not, as well as screenshots. Also tested switching between light & dark mode in HAX itself, did not fix issue. Possibly a `light-dark()` issue?

|  | Chrome | Firefox |
|--------|--------|--------|
| Light Mode | Bad | Good |
| Dark mode | Bad | Bad | 

---

### Light Mode
![image](https://github.com/user-attachments/assets/a150dc0c-972f-44b9-b4c2-02e61f8a473d)

### Dark Mode
![image](https://github.com/user-attachments/assets/560bc768-48dc-4eee-8a4e-75fb7bd926e4)

### Light Mode
![image](https://github.com/user-attachments/assets/68a40b10-7d14-4975-8cf3-50ee15bf0380)

### Dark Mode
![image](https://github.com/user-attachments/assets/84e746a3-8a3a-4c41-8095-9b940b75aac8)

**Comment by btopro** [comment]
thanks for the report, glad I caught this just before publishing as it affected several themes and block elements.
