### ISSUE TITLE
[haxor blog theme] Serving the haxor blog theme locally does not open HAX editor initially

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2086]
### Description

When I serve my HAX site locally, the HAX editor does not immediately open.  This is unique to the haxor blog theme.  The known workaround for now is to navigate to a page and refresh the page, at which point the HAX editor appears.

### Expected behavior

I expect the HAX editor to open immediately after starting the local dev server

**Comment by btopro** [comment]
Ya this is a regression in 9 unfortunately in this theme. It's one of the few themes that has no content on the homepage and that appears to be what makes it activate the editor
