### ISSUE TITLE
[hax site] Infinite loop of appending query params when reloading site pages

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2087]
### Description

If I navigate to whatsacomputertho.github.io/about in my browser URL bar, it enters an infinite loop appending query params onto the URL
https://whatsacomputertho.github.io/about/?p=/&q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/~and~q=p=/

Same thing happens if I refresh from that page

### Expected behavior

I expect the page to load when refreshing or navigating to a page's URL explicitly via the browser URL bar

**Comment by btopro** [comment]
https://github.com/haxtheweb/haxcms-nodejs/blob/main/src/boilerplate/site/404.html is the file generating this. I have yet to see someone deploy to thing.github.io without a `/whatever/`. We can account for this with a tweak to the 404 script most likely

**Comment by btopro** [comment]
you'll have to update this file but try changing 404.html to have this on the line about segmentation. It says length > 1 by default (changing to account for this)

```
      if (window.location.host.indexOf('github.io') != -1 && window.location.pathname.split('/').length > 2) {
```

**Comment by btopro** [comment]
https://github.com/haxtheweb/haxcms-nodejs/commit/30bd6d45b5967d60ef4e4e0440fba95aeb06dec8#diff-efed0b15b65b169d191c3fa4726adb1ec18e3e36f06de787c757759941e956e4R30 can see line. This is a bandaid on a bandaid. A build routine being aware of the path would be the optimal solution here. https://github.com/haxtheweb/issues/issues/2082 will hopefully forge a path now that https://github.com/haxtheweb/issues/issues/2040 is supported
