### ISSUE TITLE
[hax editor] Math configure settings text invisible, not expandable

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#2088]
### Description

The configure settings for the math element in the Hax editor appear with bright text on a bright background.  Furthermore, they cannot be expanded.

I was hoping to be able to write out a LaTeX expression and center it, but this could not be achieved using just the math element on its own.  As a workaround, I simply created a new paragraph element, aligned its text to the center, and then created a math element inside the paragraph element.  This successfully centered the LaTeX rendering.

### Expected Behavior

1. The configure settings text for the math element should be more visible
2. The math element should be "centerable" (or if it's just intended to serve as an inline element, that's fine, it can be centered via its parent block element)

**Comment by whatsacomputertho** [comment]
![Screenshot 2024-07-28 190701](https://github.com/user-attachments/assets/0c7a1176-5941-4f2c-b713-47b8eae014ec)

**Comment by btopro** [comment]
Is your expectation that this is a centered block level element with text formatting options for sizing?

**Comment by btopro** [comment]
https://github.com/haxtheweb/issues/issues/2146 will resolve this by adding legit latex support as a block level element
