### ISSUE TITLE
running npm init @haxtheweb local file issue

### ISSUE THREAD

**Issue by andyux01** [haxtheweb/issues#2089]
can not run npm init @haxtheweb
![image](https://github.com/user-attachments/assets/9e9ace87-5b4e-4d7f-ab1b-e6c965b7d077)

**Comment by btopro** [comment]
Where are you on your file system, what command did you run? Never had that before 😅

**Comment by pesaninweb** [comment]
Previously it could work with version 9, but version 9.02 doesn't work on Windows 10/11

**Comment by btopro** [comment]
Really? What's the error message?

**Comment by pesaninweb** [comment]
> Really? What's the error message?

![17223130535833124434201869390019](https://github.com/user-attachments/assets/c7bfbfa7-5d3e-45bc-bbb5-8a93f7948653)

**Comment by btopro** [comment]
Interesting.. I'll take a look at this today via automated build testing although that can only go so far without me having a windows machine. Is it possible you used a different terminal last time? It seems to have lost scope of where npm is on your system.

@zdodson21 can you try and make a site on the windows side of your computer and let me know if you run into issues?

**Comment by zdodson21** [comment]
Weirdly enough for me Git Bash and Command Prompt in Windows seemed to work ok in their default directory, while PowerShell tried to just initialize a package like a normal `npm init` statement, and my WSL threw an error, which I would have expected the opposite. Will test on my Linux machine and edit this comment with a screenshot from that.

---
## Windows Subsystem for Linux (Ubuntu / Linux Environment)
![image](https://github.com/user-attachments/assets/519ebdca-bc48-4ad4-b465-796f452c2a1a)
---
## Git Bash (Windows Environment)
![image](https://github.com/user-attachments/assets/45954588-8596-4b58-8bab-a9225d6bf89d)
---
## Command Prompt (Windows Environment)
![image](https://github.com/user-attachments/assets/6f6ab2aa-5a72-4af6-9c4d-ce42862e1f14)
---
## PowerShell (Windows Environment)
![image](https://github.com/user-attachments/assets/b2b33aab-1950-41f7-9f0d-77a70d3f28fb)

**Comment by pesaninweb** [comment]
I mean continuing with creating the single site /multi will get an error. I have tried using the solution from stackoverflow  site with the command but it still doesn't run smoothly

**Comment by btopro** [comment]
@zdodson21 are you able to make sites and can you come back and add more / administer them after the fact in the different terminals?

**Comment by andyux01** [comment]
now work on command prompt
![image](https://github.com/user-attachments/assets/3a7fb5da-3fbb-48fb-8e42-5aa88c372fd8)
