### ISSUE TITLE
Import from URL does not work

### ISSUE THREAD

**Issue by singpolyma** [haxtheweb/issues#2129]
Running `docker run --network=host node:20-alpine npx @haxtheweb/haxcms-nodejs` I then choose import and then choose HTML, it asks for a URL and I give it https://postpartumsidekick.ca/ it pops up a little progress bar in bottom right for a second and then it goes away. No error, no progress, just goes away.

Dev console says:

```
Uncaught (in promise) TypeError: n.data.filename is undefined
    importFromURL http://localhost:3000/build/es6/node_modules/@haxtheweb/app-hax/lib/v1/app-hax-steps.js:1
    handleEvent http://localhost:3000/build/es6/node_modules/lit-html/lit-html.js:6
app-hax-steps.js:1:5864
```

**Comment by btopro** [comment]
From localhost it may believe it's running locally and expect vercel endpoints for those integrations. #2103

**Comment by singpolyma** [comment]
So right now this kind of import is not expected to work from local?

**Comment by btopro** [comment]
npx command should work locally though HTML import doesn't unfortunately work the way thought of in said request
