### ISSUE TITLE
[desktop] Finish porting relevant HAXcms endpoints to nodeJS

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#215]
The desktop app could be heavily gutted and instead leverage HAXcms's nodeJS work as the basis for operating on desktop. This would allow us to largely maintain 1 code base (HAXcms) while getting a desktop app in the process as well as a nodeJS version of the platform. Open API 3.0 in documenting endpoints was enough to get large portions of this working and while it can't create sites yet it is able to load sites.

- Desktop app - https://github.com/elmsln/hax-desktop-app
- JSON API response - http://haxcms.do1.demos.elmsln.org/system/api/openapi/json
- HAXcms nodejs backend starting point - https://github.com/elmsln/HAXcms/tree/master/system/backend/nodejs

**Comment by btopro** [comment]
once we have a nodeJS based version that's able to generate new sites, save pages, add new ones, etc; we can get a desktop app from it using electron -- https://github.com/elmsln/issues/issues/215 . There is code currently in the nodejs side of haxcms found here https://github.com/elmsln/HAXcms/tree/master/system/backend/nodejs so going to system/backend/nodejs you can run yarn install and yarn start to see what i has currently. I believe last I worked on it it's in enough of a state to be able to display existing sites but can't yet create new ones or save content. A lot of the end points are started but need worked on (obviously)

**Comment by dtn9197** [comment]
I found your comment in the code. Am i meant to modify something before i run this? There seems to be a naming conflict.
![image](https://user-images.githubusercontent.com/55216005/83672177-dc26bd00-a5a3-11ea-9456-34f8241e8ba5.png)

**Comment by btopro** [comment]
This code was a mix of manual and automated porting. It's saying that `let site` is defined twice in that same function. This code is in need of debugging at some level as well so making the second `let site` just be `site` should get it to stop complaining

**Comment by btopro** [comment]
#676 if we have a development environment that's single element / project focused and has everything you need to make a site that's powering haxcms as a single instead of multitenent instance

**Comment by btopro** [comment]
https://github.com/haxtheweb/issues/issues/2008 carrying the water forward on this as it is working for a lot of them!
