### ISSUE TITLE
[bug] Update 'logo' field to reflect 'favicon'

### ISSUE THREAD

**Issue by cgldevel** [haxtheweb/issues#2179]
Location: https://iam.hax.psu.edu/cgl109/sites/grovecenterwebtraining/
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1512x982
Window size: 1505x760
Battery: 100%
Connection: 4g
Bug you experienced: Not really a bug...Not really that important, more of a note: The system uses the 'logo' field located in: Site actions > Edit Settings to define a favicon. I'm aware of this, but new users might not be aware what 'logo' actually does. Potential Fixes: Either renaming the field, or providing some descriptive text below the field that is more clear.

**Comment by cgldevel** [comment]
![field-change-example](https://github.com/user-attachments/assets/1ce06e91-455e-4942-80b0-e5d2b2ecf3bb)

**Comment by btopro** [comment]
Good suggestion; should now be like this:

```
                "title": "Favicon",
                "description": "Browser tab image / used on phones as small site logo",
```
