### ISSUE TITLE
Youtube Short Videos not working in Videos Block

### ISSUE THREAD

**Issue by Peter12G** [haxtheweb/issues#2181]
Location: https://iam.hax.psu.edu/ptr5004/sites/inart1/is-artispretentious
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
OS: Windows - 8GB RAM - 12 cores
Screen: 1920x1080
Window size: 1912x956
Battery: 100%
Connection: 4g
Bug you experienced:

Youtube short videos do not load in the video block. They can be embedded with just an HTML code, but the block doesn't recognize the links.

https://www.youtube.com/shorts/niVAxOOSLmE

**Comment by Peter12G** [comment]
This works. Thanks.

**Comment by btopro** [comment]
fixed in next release
