### ISSUE TITLE
[bug] Youtube video will not load

### ISSUE THREAD

**Issue by WilliamMRose** [haxtheweb/issues#2203]
Location: https://iam.hax.psu.edu/bmr1/sites/inart-125/readingandvideo-8
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
OS: macOS - 8GB RAM - 8 cores
Screen: 1280x800
Window size: 1266x647
Battery: 100%
Connection: 4g
Bug you experienced: The first video on this page (Post-Punk: The Early Years) consistently shows "loading..." forever when play is clicked. I have tried the original URL (https://www.youtube.com/watch?v=zblrwIdOhWU) and the share URL (https://youtu.be/zblrwIdOhWU?si=jKsOvKR8S5MUK3nn) repeatedly, but neither works. I have deleted and re-created the video player...no dice.

Also happens with second video on 
https://iam.hax.psu.edu/bmr1/sites/inart-125/readingandvideo-9

**Comment by btopro** [comment]
Others work. Maybe it's not allowed to be embedded. Try iframe based way and see if it allows it

**Comment by btopro** [comment]
![image](https://github.com/user-attachments/assets/8c351e18-c07f-4073-9031-b113cc3bc739)
