### ISSUE TITLE
[HAXapi] Add API call support to package.json directly via nodejs package

### ISSUE THREAD

**Issue by btopro** [haxtheweb/issues#352]
@heyMP Might know a good way to do this but basically I think we should be able to do the following:
- from a project: `yarn run api --cmd="addPage" --title="New page here" --body="<p>newcontent</p>"`

If we did this for a few it would make some of the automation / docker stuff I know @heyMP wants to do easier.

Ideally we'd call the same function / file as the express app does when hitting the `/system/api/createNewSite` end point (yet to be made)

**Comment by btopro** [comment]
@whatsacomputertho this might be a good one that overlaps w/ your other projects / interests. Effectively, we need a way of saying "ok so we build url.com/api/apiCallRoute but now we want to mirror that on the CLI". This way you could say run a simulation of your football game entirely via commandline which would then be useful for building tests in a CI service to ensure it's running correctly, but also in our purposes that'd allow us to run something like `hax addPage sitename "Test page name" --contents=./filepath.html` and get a new page added to the site named `sitename` with contents taken from that file path

**Comment by btopro** [comment]
#699 related because it would then be able to leverage it

**Comment by btopro** [comment]
exists

**Comment by whatsacomputertho** [comment]
@btopro I was just about to add this into my sprint backlog too ;)
