### ISSUE TITLE
[HAXdesktop] File submenu item should publish HAX sites to a remote git repo

### ISSUE THREAD

**Issue by whatsacomputertho** [haxtheweb/issues#687]
This would involve...
- Going into the main.js file within the HAXdesktop repo
- Adding some lines of code within the click function for the submenu item labeled "Publish"
- My approach involved having this code essentially build a shell script using node-powershell with system commands and git commands which would be invoked on click and then its output would be console.logged in case an error occurs
- Consider that there is no variable in the script tracking the currently "Opened" directory; might need to be added
- Consider also that there is no variable storing a path/URL to any remote repo; also probably should exist for these purposes
- Update the comments I left related to this issue also

**Comment by btopro** [comment]
https://haxtheweb.org/site.json the JSON Outline Schema spec has publishing info in it. I'd suggest firing up haxcms https://github.com/elmsln/haxcms using ddev or docker.

**Comment by btopro** [comment]
publishing works on command line, desktop app should add things like this but currently it completely aligns /w rest of projects so really, we need nodejs to allow publishing via UI and then move from there
