### ISSUE TITLE
cms-token rendering issue after book redirects

### ISSUE THREAD

**Issue by JackWillDavis** [haxtheweb/issues#918]
We've come across a bug in ELMSLN v1.2.1 which breaks cms-token rendering when a user is automatically bumped from a parent page into the next one inside mooc-content.

As part of some of our courses, we link directly to sections of a book which are relevant to particular modules instead of always accessing the course through the homepage. These links are set up on parent pages which don't display content itself. So, ones which display as:

![image](https://user-images.githubusercontent.com/2301874/145984862-14055f23-0b4c-439c-9c25-2d86f8bee3e0.png)

Previously, the user landing on this page would simply push them onto the next page. In v1.2.1, this redirect still happens but it causes an issue where there is an endless loading spinner for cms-token assets. This issue persists until a hard refresh of the browser window.

We've managed to get around this for now by manually checking the page we're about to link to and, if it doesn't have any content, pushes the learner onto the next available page via PHP so that mooc-content isn't doing the redirect itself.

### Steps to reproduce the issue

* Find an empty parent page with child pages
* Attempt to link directly to that parent page from a new session
* mooc-content should bump the user to the next page as expected but cms-tokens should fail to load consistently when clicking through subsequent pages

I'm not entirely sure where the actual issue lies, I'm assuming it might be it's redirecting before completing the initialisation of mooc-content which is breaking something? Let me know if you need any other info!

**Comment by rickhumphries** [comment]
related: #912
